services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  phpcacheadmin:
    image: robinn/phpcacheadmin:latest
    container_name: phpcacheadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PCA_REDIS_0_HOST: redis
      PCA_REDIS_0_PORT: 6379
    depends_on:
      - redis
    links:
      - redis

volumes:
  redis_data:
